my_app/urls.py
from django.urls import path
from my_app import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'my_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('add_notes/', views.createNotes, name='add_notes'),
    path('notes/', views.viewNotes, name='notes'),
    path('update_notes/<str:pk>/', views.updateNotes, name='update_notes'),
    path('delete_notes/<str:pk>/', views.deleteNotes, name='delete_notes'),
    path('data/', views.getData, name="data"),
    path('load-more', views.loadMore, name="load-more"),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

my_first_django_app/urls.py
from django.urls import path, include
from django.contrib import admin
from my_app import views

urlpatterns = [
    path('my_app/', include('my_app.urls')),
    path("admin/", admin.site.urls),
    path('logout/', views.user_logout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('', include('my_app.urls'))
    #path("accounts/", include("django.contrib.auth.urls")),
]

my_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


class Notes(models.Model):
    ordering = ['-id']
    STATUS = (
    ('Active','active'),
    ('In-active','in-active')
    )
    title = models.TextField(max_length=160, null=True, blank=True)
    owner = models.ForeignKey(User, related_name='user', on_delete=models.SET_NULL, null=True)
    createdOn = models.DateTimeField(auto_now_add=True, null=True)
    updatedOn = models.DateTimeField(auto_now=False, null=True)
    description = models.CharField(max_length=5000, null=True, blank=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    
    
    def __str__(self):
         return self.title
    
    # @property 
    # def author(self):
    #     return self.createdBy.username

my_app/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserProfileInfo, Notes
from django.core.validators import validate_email


class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(), required=True)
    email = forms.EmailField(widget=forms.EmailInput(), required=True)
    password = forms.CharField(
    widget=forms.PasswordInput(), required=True, min_length=10, max_length=100)
    first_name = forms.CharField(widget=forms.TextInput(), required=True)
    last_name = forms.CharField(widget=forms.TextInput(), required=True)

    class Meta():
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class NotesForm(forms.ModelForm):
    STATUS = (
    ('Active','active'),
    ('In-active','in-active')
    )
    description = forms.CharField(widget=forms.Textarea)
    title = forms.CharField(widget=forms.TextInput(), required=True)
    status = forms.CharField(widget=forms.Select(choices=STATUS), required=True)

    class Meta():
        model = Notes
        fields = ('description','title','status')

my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm, UserProfileInfoForm, NotesForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from my_app.models import *
from django.shortcuts import get_object_or_404
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.core.paginator import Paginator
from django.db.models import Q, Exists, OuterRef
from django.core import serializers 
from my_app.serializers import NoteSerializer
import math

def index(request):
    return render(request, 'my_app/index.html')

def viewNotes(request):
    if request.user.is_authenticated:
        keyword = request.GET.get('search') or ''

        if (keyword != ''):
            q_object = Q(owner=request.user.id) and Q(title__icontains=keyword) | Q(description__icontains=keyword) | Q(id__icontains=keyword) | Q(owner__username=keyword) | Q(owner__first_name=keyword) | Q(owner__last_name=keyword)
            notes_list = Notes.objects.filter(q_object)
        else:
            notes_list = Notes.objects.filter(owner=request.user.id)

        # notes_list = Notes.objects.get_queryset().order_by('id')
        page = request.GET.get('page', 1)

        paginator = Paginator(notes_list, 5)
        try:
            notes = paginator.page(page)
        except PageNotAnInteger:
            notes = paginator.page(1)
        except EmptyPage:
            notes = paginator.page(paginator.num_pages)

        total = notes_list.count()
        lastPage = total / 5
    else:
        notes = Notes.objects.all()
        keyword = ''

    return render(request, 'my_app/notes_list.html', {'notes': notes, 'query':keyword, 'currentPage': page, 'lastPage': math.ceil(lastPage), 'total':total})

def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/my_app/')

    if request.method == 'POST':
        err_msg = ''
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username == '' or password == '':
            err_msg = 'Please enter your username and password'

            return render(request, 'my_app/login.html', {'err': err_msg})

        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('../../my_app/')

            else:
                err_msg = 'Account is in-active'
                return render(request, 'my_app/login.html', {'err': err_msg})
                # return HttpResponse('Account not active')

        else:
            # print("Username: {} and password {}".format(username, password))
            err_msg = 'Login failed'

            return render(request, 'my_app/login.html', {'err': err_msg})
            # return HttpResponse('Login failed')

    else:
        return render(request, 'my_app/login.html')


def register(request):
    registered = False

    if request.user.is_authenticated:
        return HttpResponseRedirect('/my_app/')

    if request.method == "POST":
        username = request.POST.get('username')
        firstname = request.POST.get('first_name')
        lastname = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        conf_password = request.POST.get('conf_password')
        portfolio = request.POST.get('portfolio_site')
        hasErrors = False

        if (firstname == ""):
            hasErrors = True
            messages.error(request, 'Firstname is required')

        if (firstname.isalpha is False):
            hasErrors = True
            messages.error(request, 'Firstname should contains letters only')

        if (lastname == ""):
            hasErrors = True
            messages.error(request, 'Lastname is required')

        if (lastname.isalpha is False):
            hasErrors = True
            messages.error(request, 'Lastname should contains letters only')
        
        if (email == ""):
            hasErrors = True
            messages.error(request, 'Email address is required')

        if (password == ""):
            hasErrors = True
            messages.error(request, 'Password is required')

        if password and len(password) < 9:
            hasErrors = True
            messages.error(request, 'Password length must be 10 characters long')

        if (conf_password == ""):
            hasErrors = True
            messages.error(request, 'Password confirmation is required')
        
        if (portfolio == ""):
            hasErrors = True
            messages.error(request, 'Portfolio site address is required')
        
        if (password and password != conf_password):
            hasErrors = True
            messages.error(request, 'Password confirmation do not match')
        
        if (email and User.objects.filter(email=email)):
            hasErrors = True
            messages.error(request, 'Email already exist')
        
        if (username and User.objects.filter(username=username)):
            hasErrors = True
            messages.error(request, 'Username already exist')

        if (hasErrors is True):
            return render(request, 'my_app/register.html', {'registered': registered})
    
        user = User.objects.create_user(username, email, password)
        user.first_name = firstname
        user.last_name = lastname
        #user.set_password(user.password)
        user.save()

        profile = UserProfileInfo.objects.create()
        profile.portfolio_site = portfolio
        profile.user = user

        if 'profile_pic' in request.FILES:
            profile.profile_pic = request.FILES['profile_pic']
           
        profile.save()
        registered = True

        messages.success(request, 'Registered successfully.')

        return render(request, 'my_app/register.html', {'registered': registered})
        #return HttpResponseRedirect('/my_app/register')

    else:
        return render(request, 'my_app/register.html', {'registered': registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../../my_app/')
    # return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    user = get_object_or_404(User, id=request.user.id)
    user_info = get_object_or_404(UserProfileInfo, user_id=request.user.id)

    if request.method == 'POST':
        firstname = request.POST.get('first_name')
        lastname = request.POST.get('last_name')
        password = request.POST.get('password')
        old_password = request.POST.get('old_password')
        portfolio = request.POST.get('portfolio_site')

        if (firstname == ""):
            err_msg = 'Firstname is required'
            return render(request, 'my_app/profile.html', {'user': user, 'user_info':user_info,'err': err_msg})
        
        if (lastname  == ""):
            err_msg = 'Lastname is required'
            return render(request, 'my_app/profile.html', {'user': user, 'user_info':user_info,'err': err_msg})
        
        if (portfolio == ""):
            err_msg = 'Portfolio is required'
            return render(request, 'my_app/profile.html', {'user': user, 'user_info':user_info,'err': err_msg})

        if (request.POST.get('password') != ""):
            if (request.POST.get('password') != request.POST.get('confirm_password')):
                err_msg = 'Password confirmation do not match'
                return render(request, 'my_app/profile.html', {'user': user, 'user_info':user_info,'err': err_msg})

            if (user.check_password(old_password) == False):
                err_msg = 'Old password do not match'
                return render(request, 'my_app/profile.html', {'user': user, 'user_info':user_info,'err': err_msg})

        user.first_name = firstname
        user.last_name = lastname

        if (request.POST.get('password') != ""):
            user.password = make_password(password)
        user.save()
        update_session_auth_hash(request, user)

        user_info.portfolio_site = portfolio

        if 'profile_pic' in request.FILES:
            user_info.profile_pic = request.FILES['profile_pic']
           
        user_info.save()

        success_msg = 'Profile updated successfully'
        return render(request, 'my_app/profile.html', {'user': user, 'user_info':user_info, 'suc': success_msg})

    return render(request, 'my_app/profile.html', {'user': user, 'user_info': user_info})


@login_required
def createNotes(request):

    if request.method == 'POST':
        notes_form = NotesForm(data=request.POST)
        print(request.POST)

        if notes_form.is_valid():
            created_by = get_object_or_404(User, id=request.user.id)
            instance = notes_form.save(commit=False)
            instance.owner = created_by
            instance.save()

            messages.success(request, 'Notes added Successfully.')
            return HttpResponseRedirect('/my_app/add_notes')

    notes_form = NotesForm()
    return render(request, 'my_app/add_notes.html', {'notes_form': notes_form})

@login_required
def updateNotes(request, pk):
    # notes = Notes.objects.get(id=pk)
    # Notes.objects.filter(id=pk)
    notes = get_object_or_404(Notes, id=pk)
    notes_form = NotesForm(instance=notes)

    if request.method == 'POST':
        notes_form = NotesForm(data=request.POST, instance=notes)

        if notes_form.is_valid():
            updated_on = datetime.now()
            instance = notes_form.save(commit=False)
            instance.updatedOn = updated_on
            instance.save()

templates/my_app/add_notes.html
{% extends "my_app/base.html" %}

{% block body_block %}

<div class="" style="margin-top: 15px">
  <h3>Add Notes</h3>
  {% if messages %} {% for message in messages %}
  <div
    class="callout {% if message.tags %} {{ message.tags }} {% endif %}"
    data-closable
  >
    {{ message }} <a href="{% url 'my_app:notes' %}">Go back to notes list</a>
    <button
      class="close-button"
      aria-label="Dismiss alert"
      type="button"
      data-close
    >
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} {% endif %}
  <div class="card" style="margin-top: 15px; border-radius: 5px">
    <div class="card-section">
      <form method="post" id="notes_form">
        {% csrf_token %} 
        <!-- {{ notes_form.as_p }} -->
        <label for="id_title">Title:</label>
        <input type="text" name="title" id="id_title" >
        <label for="id_status">Status:</label>
        <select name="status" id="id_status">
          <option value="Active">Active</option>
          <option value="In-active">In active</option>
        </select>
        <label for="id_description">Notes:</label>
        <textarea name="description" id="id_description" class="summernote"></textarea>
        <br/>
        <button type="submit" class="button">Add</button>
      </form>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
      $('.summernote').summernote({
        height: 300,
        placeholder: 'type starting with @',
        hintMode: 'words',
        hintSelect: 'next',
        hint: {
          mentions: [
            {
              name: 'Jayden Smith',
              url: 'http://example.org/person/jayden-smith'
            },
            {
              name: 'Peter Pan',
              url: 'http://example.org/person/peter-pan'
            },
            {
              name: 'Lorca',
              url: 'http://example.org/person/lorca'
            },
            {
              name: 'David Summer',
              url: 'http://example.org/person/david-summer'
            }
          ],
          match: /\B@([a-z ]*)/i,
          search: function (keyword, callback) {
            callback($.grep(this.mentions, function (item) {
              return item.name.toLowerCase().indexOf(keyword.toLowerCase()) == 0;
            }));
          },
          template: function(item) {
            return item.name;
          },
          content: function (item) {
            return $('<a>')
                .attr('href', item.url)
                .text('@' + item.name)
                .get(0);
          }
        }
      });
      $('#notes_form').on('submit', function(e){
        e.preventDefault();
        var note = $('textarea').val();
        var title = $('#id_title').val();
        var status = $('#id_status').val();

        if (!title || title == '') {
            alert('Please add a title');
            return;
        } 

        if (!note || note == '') {
            alert('Please add a note');
            return;
        } 
        this.submit();
      });
 });
</script>
{% endblock %}

templates/my_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>My First Django App</title>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css"  />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/motion-ui@1.2.3/dist/motion-ui.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation-prototype.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation-rtl.min.css"/>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/js/foundation.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/summernote-lite.css' %}" />
    <script src="{% static 'js/summernote-lite.js' %}"></script>
    <link rel="stylesheet" rel="stylesheet" href="{% static 'css/custom.css' %}">    
  </head>
 
  <body>
    <div class="off-canvas position-left" id="offCanvas" data-off-canvas>
      <!-- Your menu or Off-canvas content goes here -->
      <ul class="vertical menu" data-responsive-menu="drilldown medium-accordion" style="max-width: 250px;">
        <li>
          <a href="{% url 'my_app:index' %}">Home</a>
          <!-- <ul class="vertical menu">
            <li>
              <a href="#">Item 1A</a>
              <ul class="vertical menu">
                <li><a href="#">Item 1A</a></li>
                <li><a href="#">Item 1B</a></li>
                <li><a href="#">Item 1C</a></li>
                <li><a href="#">Item 1D</a></li>
                <li><a href="#">Item 1E</a></li>
              </ul>
            </li>
            <li><a href="#">Item 1B</a></li>
          </ul> -->
        </li>
        <li>
          <a href="{% url 'my_app:profile' %}">Profile</a>
        </li>
        <li>
          <a href="{% url 'my_app:notes' %}">Note lists</a>
        </li>
        <li>
          <a href="{% url 'my_app:add_notes' %}">Create note</a>
        </li>
      </ul>
    </div>
    <div class="off-canvas-content" data-off-canvas-content>
      <!-- Your page content lives here -->
      <div
        class="title-bar"
        data-responsive-toggle="responsive-menu"
        data-hide-for="medium"
      >
        <button
          class="menu-icon"
          type="button"
          data-toggle="responsive-menu"
        ></button>
        <div class="title-bar-title">My First Django App</div>
      </div>

      <div class="top-bar" id="responsive-menu">
            <div class="top-bar-left show-for-large">
              <ul class="menu">
                {% if user.is_authenticated %} 
                  <li class="menu-text"><span class="menu-icon" data-toggle="offCanvas"></span></li>
                {% endif %}
                <li class="menu-text" data-hide-for="small">My First Django App</li>
              </ul>
            </div>
            <div class="top-bar-right">
              <ul class="dropdown menu" data-dropdown-menu>
                <li class="has-submenu">
                  <a href="{% url 'my_app:index' %}">Home</a>
                  <ul class="submenu menu vertical" data-submenu>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'my_app:profile' %}">Profile</a></li>
                    <li><a href="#" data-toggle="logoutModal">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'my_app:login' %}">Login</a></li>
                    <li><a href="{% url 'my_app:register' %}">Register</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    {% endif %}
                  </ul>
                </li>
                <li><a href="#0">About-us</a></li>
                <li><a href="#0">Contact-us</a></li>
                
              </ul>
              <!-- <ul class="menu">
                <li><input type="search" placeholder="Search" /></li>
                <li><button type="button" class="button">Search</button></li>
              </ul> -->
        </div>
      </div>

      <div class="grid-container">
        {% block body_block %} {% endblock %}
        {% if user.is_authenticated %}
          <div class="reveal" id="logoutModal" data-reveal data-close-on-click="true" data-animation-in="slide-in-down" data-animation-out="slide-out-up">
            <div style="padding: 10px;">
              <h3>Are you sure you want to logout already</h3>
              <a class="button alert" href="{% url 'logout' %}">Yes</a>
              <button class="close-button" data-close aria-label="Close modal" type="button">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </div>
        {% endif %}

        <div class="cell small-1 medium-3 large-4 loader margin-bottom-3 loader">
          <div class="sk-fading-circle">
              <div class="sk-circle1 sk-circle"></div>
              <div class="sk-circle2 sk-circle"></div>
              <div class="sk-circle3 sk-circle"></div>
              <div class="sk-circle4 sk-circle"></div>
              <div class="sk-circle5 sk-circle"></div>
              <div class="sk-circle6 sk-circle"></div>
              <div class="sk-circle7 sk-circle"></div>
              <div class="sk-circle8 sk-circle"></div>
              <div class="sk-circle9 sk-circle"></div>
              <div class="sk-circle10 sk-circle"></div>
              <div class="sk-circle11 sk-circle"></div>
              <div class="sk-circle12 sk-circle"></div>
          </div>
        </div>
      </div>
    </div>
  </body>
  <script>
    $(document).foundation();
    window.addEventListener("load", function () {
        const loader = document.querySelector(".loader");
        loader.className+="  hidden";
    })
  </script>
</html>

templates/my_app/register.html
{% extends "my_app/base.html" %} {% block body_block %}
<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell large-6 small-12">
      <div class="card {% if registered == False and messages %} animate__animated animate__shakeX {% endif %}" style="margin-top: 15px; border-radius: 5px">
        <div class="card-section">
          <h3>Sign-up</h3>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            <!-- {{ user_form.as_p }}
            {{ profile_form.as_p }} -->
            <p>
              <label for="id_username">Username:</label>
              <input type="text" name="username" id="username" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'username')">
            </p>
            <p>
              <label for="id_email">Email:</label>
              <input type="email" name="email" id="email" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'email')" >
            </p>
            <p>
              <label for="id_password">Password:</label>
              <input type="password" name="password" maxlength="100" minlength="10" id="password" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'password')">
            </p>
            <p>
              <label for="id_password">Confirm Password:</label>
              <input type="password" name="conf_password" maxlength="100" minlength="10" id="conf_password" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'conf_password')">
            </p>
            <p>
              <label for="id_first_name">First name:</label>
              <input type="text" name="first_name" id="firstname" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'firstname')">
            </p>
            <p>
              <label for="id_last_name">Last name:</label>
              <input type="text" name="last_name" id="lastname" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'lastname')">
            </p>
            <p>
              <label for="id_portfolio_site">Portfolio site:</label>
              <input type="url" name="portfolio_site" maxlength="200" id="portfolio_site" class="{% if registered == False and messages %} error_input {% endif %}" onchange="checkField(this.value, 'portfolio_site')">
            </p>
            <p>
              <input style="display: none;" type="file" name="profile_pic" accept="image/*" id="profile_pic" >
              <label for="profile_pic">
                <span><i class="fa fa-camera"></i>&nbsp;Upload your profile photo</span>
              </label>
              <img id="img" src="https://dummyimage.com/200x200/eeeeee/aaa" alt="your profile image"  width="200" height="200"/>
            </p>
            <button type="submit" class="button" >Register</button>
          </form>
        </div>
      </div>
    </div>
    <div class="cell large-6 small-12">
      {% if messages %} 
          {% if registered == True %} 
            <div class="callout success animate__animated animate__fadeIn callout-mod" data-closable>
              <ul style="list-style: none;">
              {% for message in messages %}
                  <li>
                      <strong style="color: darkgreen; font-weight: 300;"><i class="fa-solid fa-circle-check"></i>&nbsp;{{ message }}</strong>    
                    <button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span>
                    </button>
                  </li>
                {% endfor %}
              </ul>
            </div>
          {% else %} 
            <div class="callout alert animate__animated animate__fadeIn callout-mod" data-closable>
              <span style="color:crimson; font-weight: 300;"><i class="fa-solid fa-circle-exclamation"></i>&nbsp;Please review the following errors and try again</span>
                <ul style="padding: 5px 20px;">
                {% for message in messages %}
                  <li>
                    <strong style="color:crimson; font-weight: 300;">{{ message }}</strong> 
                    <button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span>
                    </button>
                  </li>
                {% endfor %}
              </ul>
            </div>
          {% endif %}
    {% endif %}
    </div>
  </div>
</div>

<script>
  function checkField(val, field) {
    if (val) {
        $('#'+field).removeClass('error_input');
    } else {
        $('#'+field).addClass('error_input');
    }
  }
  
  $('#img').hide();
  $('#del').hide();
  profile_pic.onchange = evt => {
  const [file] = profile_pic.files
  if (file) {
    $('#img').fadeIn();
    img.src = URL.createObjectURL(file)
    $('#del').fadeIn();
  }
}
</script>
{% endblock %}

templates/my_app/update_notes.html
{% extends "my_app/base.html" %} {% block body_block %}

<div class="" style="margin-top: 15px">
  <h3>Edit Notes</h3>
  {% if messages %} {% for message in messages %}
  <div
    class="callout {% if message.tags %} {{ message.tags }} {% endif %}"
    data-closable
  >
    {{ message }}   <a href="{% url 'my_app:notes' %}">Go back to notes list</a>
    <button
      class="close-button"
      aria-label="Dismiss alert"
      type="button"
      data-close
    >
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} 
  {% endif %}
  <div class="card" style="margin-top: 15px; border-radius: 5px">
    <div class="card-section">
      <form method="post" id="notes_form">
        {% csrf_token %} 
        <!-- {{ notes_form.as_p }} -->
        <label for="id_title">Title:</label>
        <input type="text" name="title" id="id_title" value="{{ notes_form.title.value }}" >
        <label for="status">Status:</label>
        <select name="status" id="id_status">
          <option value="Active" {% if notes_form.status.value == "Active" %} selected {% endif %} >Active</option>
          <option value="In-active" {% if notes_form.status.value == "In-active" %} selected {% endif %} >In active</option>
        </select>
        <label for="title">Notes:</label>
          <textarea name="description" class="summernote"></textarea>
          <br/>
        <button type="submit" class="button">Update</button>
        <a href="{% url 'my_app:index' %}" class="button">Cancel</a>
      </form>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $('.summernote').summernote({
        height: 300,
        placeholder: 'type starting with @',
        hintMode: 'words',
        hintSelect: 'next',
        hint: {
          mentions: [
            {
              name: 'Jayden Smith',
              url: 'http://example.org/person/jayden-smith'
            },
            {
              name: 'Peter Pan',
              url: 'http://example.org/person/peter-pan'
            },
            {
              name: 'Lorca',
              url: 'http://example.org/person/lorca'
            },
            {
              name: 'David Summer',
              url: 'http://example.org/person/david-summer'
            }
          ],
          match: /\B@([a-z ]*)/i,
          search: function (keyword, callback) {
            callback($.grep(this.mentions, function (item) {
              return item.name.toLowerCase().indexOf(keyword.toLowerCase()) == 0;
            }));
          },
          template: function(item) {
            return item.name;
          },
          content: function (item) {
            return $('<a>')
                .attr('href', item.url)
                .text('@' + item.name)
                .get(0);
          }
        }
      });

      $('#notes_form').on('submit', function(e){
          e.preventDefault();
          var note = $('textarea').val();
          var title = $('#id_title').val();

          if (!title || title == '') {
              alert('Please add a title');
              return;
          } 
          
          if (!note || note == '') {
              alert('Please add a note');
              return;
          } 
          this.submit();
      });

      var markupStr = "{{ notes_form.description.value|safe }}";
      
      $('.summernote').summernote('code', markupStr);
  });
  </script>
{% endblock %}